{% set name = "pyrmsd" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/salilab/pyRMSD/archive/v{{ version }}.tar.gz
  sha256: 9d0c14ae8cbdc6ce069c607b59c0db9d91133d559a6272b0a6bc2a2cc68090cb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
  host:
    - pip
    - python
    - numpy
  run:
    - python

test:
  source_files:
    - src/calculators/test/
    - pyRMSD/test/
  imports:
    - pyRMSD.RMSDCalculator
    - pyRMSD.availableCalculators
    - pyRMSD.matrixHandler
    - pyRMSD.utils.proteinReading
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/salilab/pyRMSD
  summary: Efficiently calculate RMSDs for large structure sets
  license: MIT
  license_file: LICENSE
  description: |
    pyRMSD is a small Python package that aims to offer an integrative
    and efficient way of performing RMSD calculations of large sets of
    structures. It is specially tuned to do fast collective RMSD
    calculations, as pairwise RMSD matrices.

    Note that this package does not currently include any CUDA calculators.

    See [the pyRMSD website](https://github.com/salilab/pyRMSD)
    and the [publication](https://doi.org/10.1093/bioinformatics/btt402)
    for more details.
  dev_url: https://github.com/salilab/pyRMSD

extra:
  recipe-maintainers:
    - benmwebb
